### ISSUE TITLE
Build the Supplier DELETE Service

### ISSUE THREAD

**Issue by snr6450** [nyusuppliers/suppliers#14]
**As a**shopping website manager
**I need** to be able to delete suppliers by id 
**So that**  the suppliers' list is consistent with only valid suppliers

**Assumptions:** 

* The DELETE service will be part of the supplier_service.py file
* The test cases will be part of the test_supplier_service.py file

**Acceptance Criteria:**

```
Given a list of ids of suppliers through a dropdown list
When API call on route "DELETE /suppliers/{id}"
Then the service should delete the supplier with the corresponding id and their related products with return code 204. 
```

**Comment by snr6450** [comment]
@gdrdrdr we can only start working on issues from top of sprint backlog

**Comment by gdrdrdr** [comment]
Got it. Thanks
