### ISSUE TITLE
Build the Supplier CREATE Service

### ISSUE THREAD

**Issue by ssr8998** [nyusuppliers/suppliers#2]
**As a** User
**I need** the functionality to create all suppliers with their corresponding attributions
**So that** we can add all available suppliers

**Assumptions:**

- The create service will be part of the supplier_service.py file
- The test cases will be part of the test_supplier_service.py file

**Acceptance Criteria:**

```
When I call 'POST /suppliers/' 
Then the system will create a new supplier with the corresponding posted data and return code 201 plus supplier list.
```

**Comment by gdrdrdr** [comment]
**As a** 
**I need** 
**So that** 

**Assumptions:**

-
-

**Acceptance Criteria:**

```


```
