### ISSUE TITLE
Integrate Pull Requests with Slack channel

### ISSUE THREAD

**Issue by gdrdrdr** [nyusuppliers/suppliers#51]
**As a** Developer
**I need** to integrate pull requests with the slack channel
**So that** the team will be notified when there is a pull request and approve it or provide feedback timely

**Acceptance Criteria:**

```
When someone raises a pull request
Then the slack channel will be notified
```

**Comment by gdrdrdr** [comment]
Installed GitHub in Slack

**Comment by gdrdrdr** [comment]
Issue closed by joyceluyy
#55 Add error handlers for REST API
<https://github.com/nyusuppliers/suppliers|nyusuppliers/suppliers>nyusuppliers/suppliers | Jul 12th
9:42
Pull request merged by joyceluyy
#72 add error handler
nyusuppliers/suppliers | Yesterday at 1:17 AM

**Comment by snr6450** [comment]
Works perfectly!
