### ISSUE TITLE
Create a .travis.yml file and configure Travis CI

### ISSUE THREAD

**Issue by gdrdrdr** [nyusuppliers/suppliers#52]
**As a** developer 
**I need** an automated way to run test when someone pushes to the master branch or submits a Pull Request 
**So that** we know the new changes did not introduce more bugs and have proper test coverage

**Assumptions:**

* Use Travis CI to run the tests on every pull request

**Acceptance Criteria:**

```
Setup Travis CI to monitor the GitHub repository 
When there is any push or pull request 
Then Travis CI will run test cases and showing the test status and code coverage on README.md file
```

**Comment by joyceluyy** [comment]
Changed merged to main
