### ISSUE TITLE
Crate a python Flask Could Foundry application in IBM 

### ISSUE THREAD

**Issue by joyceluyy** [nyusuppliers/suppliers#53]
**As a** Developer
**I need** setup the Could Foundry platform in IBM Could 
**So that** we can deploy the application to the cloud 

**Assumptions:**

* The application will be deployed on the Cloud Foundry platform in the IBM cloud

**Acceptance Criteria:**

```
- Invite the members of the team to the IBM Cloud Account
- Create a Python Flask Cloud Foundry application in IBM Cloud - US South, following the required naming convention 
```

**Comment by snr6450** [comment]
Default (Hello world) Application is running successfully on https://nyu-supplier-service-sum21.us-south.cf.appdomain.cloud/
