### ISSUE TITLE
Use Selenium to conduct the UI testing

### ISSUE THREAD

**Issue by gdrdrdr** [nyusuppliers/suppliers#58]
**As a** Developer
**I need** to use Selenium to conduct the BDD UI testing 
**So that** there should be no direct connection to the service from the BDD tests

**Assumptions:**

* BDD .feature file and accompanying steps.py files are already set up

**Acceptance Criteria:**

```
When the developers run the UI testing
Then the test will run using Selenium
```

**Comment by joyceluyy** [comment]
Closing the story as each BDD scenarios will be addressed in the separated stories.
