### ISSUE TITLE
Add Swagger Docs

### ISSUE THREAD

**Issue by snr6450** [nyusuppliers/suppliers#60]
**As a** developer
**I need** the API documented in Swagger
**So that**  I can easily understand how to use the API

**Assumptions:**

* Ability to leverage Swagger support for Python

**Acceptance Criteria:**

```
Given I have the Swagger documentation set up
When I follow the `/api-docs` URL
Then I should get the documentation JSON in Swagger format
```

**Comment by gdrdrdr** [comment]
swagger docs created
