### ISSUE TITLE
Add Build Stage to the pipeline

### ISSUE THREAD

**Issue by snr6450** [nyusuppliers/suppliers#61]
**As** a developer
**I need** CICD build pipeline to automatically run the (TDD) unit test when changes are applied to the master branch
**So that** we can ensure the newly added changes do not introduce errors

**Assumptions:**

* The Build stage will run TDD test andn call the Deploy stage 

Acceptance Criteria:
```
When new changes applied to the github repository main branch 
Then the build pipeline will be automatically triggered and run the TDD unit tests 
```

**Comment by joyceluyy** [comment]
- Crated the build stage on IBM cloud continuous delivery
- Link the new elephant sql db to the build stage
