### ISSUE TITLE
Add a Dev Deployment Stage to the pipeline

### ISSUE THREAD

**Issue by joyceluyy** [nyusuppliers/suppliers#62]
**As a** developer
**I need** to enhance my delivery pipeline
**So that** a dev environment is deployed once unit testing passes

**Assumptions:**

* The application will be deployed on the Cloud Foundry platform in the IBM cloud

**Acceptance Criteria:**

```
Given the delivery pipeline has been set up using appropriate cloud tools
When I deploy to the cloud and my unit tests in the Build stage have passed
Then the dev environment is automatically deployed
and the deployment will fail if requirements have not been met

```

**Comment by snr6450** [comment]
Deploy set up and build passing on ibm cloud
