### ISSUE TITLE
Add a Integration Test Stage to the pipeline

### ISSUE THREAD

**Issue by snr6450** [nyusuppliers/suppliers#63]
**As a** developer
**I need** to enhance my delivery pipeline
**So that** a Integration Test environment is deployed once unit testing passes

**Assumptions:**

* The application will be deployed on the Cloud Foundry platform in the IBM cloud

**Acceptance Criteria:**

```
Given the delivery pipeline has been set up using appropriate cloud tools
When I deploy to the cloud and my unit tests in the Integration Test stage have passed
Then the test environment is automatically deployed
and the deployment will fail if requirements have not been met

```

**Comment by gdrdrdr** [comment]
added the Test stage in the Pipeline
