### ISSUE TITLE
Add BDD Scenario for DELETE

### ISSUE THREAD

**Issue by joyceluyy** [nyusuppliers/suppliers#68]
**As a** developer 
**I need** add BDD scenario for DELETE in the .feature file
**So that** we can test the RESTful DELETE service

**Assumptions:**

* Write the feature using Gherkin syntax which is understood by the behave tool

**Acceptance Criteria:**

```
When the user set the "name" field to an existing supplier 
And press the "Search" button 
Then the UI should return that user in the results 
When the user press the "Delete" button 
Then the UI should return message "Supplier has been Deleted!"
When the user press the "Clear" button
And press the "Search" button 
Then the user should not see the deleted supplier in the results
```

**Comment by snr6450** [comment]
@ssr8998 could you pls work on UI creation instead next? we have other items in priority before getting to this issue.

**Comment by ssr8998** [comment]
ok.
