### ISSUE TITLE
Add BDD Scenario for PENALIZE

### ISSUE THREAD

**Issue by joyceluyy** [nyusuppliers/suppliers#71]
**As a** developer 
**I need** add BDD scenario for PENALIZE in the .feature file
**So that** we can test the RESTful PENALIZE service

**Assumptions:**

* Write the feature using Gherkin syntax which is understood by the behave tool

**Acceptance Criteria:**
```
When the user select a supplier on the UI 
And press "Penalize" button 
Then the UI should return message "Success"
When the user copy the "id" field 
And press the "Clear" button 
And paste the "id" field 
And press "Retrieve" button
Then the UI should return the supplier record with rating decreased by 1 
```

**Comment by gdrdrdr** [comment]
pair coding with Zunduo
