### ISSUE TITLE
Create a new Space in your Cloud Foundry account called: prod

### ISSUE THREAD

**Issue by gdrdrdr** [nyusuppliers/suppliers#90]
**As a** Developer  
**I need** to create a new Cloud Foundry Space for production
**So that**  the IBM Cloud CD Pipeline can automatically deploy the product

**Assumptions:**

* A new Cloud Foundry Space is created.

**Acceptance Criteria:**

```
When running Prod Stage
Then the product will be deployed to the new space
```

**Comment by snr6450** [comment]
i've created the prod space on cloud. do check and let me know if everyone could see/access it

**Comment by snr6450** [comment]
Prod space now available in ibm cloud
